// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_instances.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgentInstanceShare = `-- name: CreateAgentInstanceShare :one
INSERT INTO agent_instance_share (id, instance_id, permission, token_hash, data) VALUES ($1, $2, $3, $4, $5)
RETURNING id, instance_id, permission, token_hash, data
`

type CreateAgentInstanceShareParams struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Permission string
	TokenHash  []byte
	Data       []byte
}

func (q *Queries) CreateAgentInstanceShare(ctx context.Context, arg CreateAgentInstanceShareParams) (AgentInstanceShare, error) {
	row := q.db.QueryRow(ctx, createAgentInstanceShare,
		arg.ID,
		arg.InstanceID,
		arg.Permission,
		arg.TokenHash,
		arg.Data,
	)
	var i AgentInstanceShare
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Permission,
		&i.TokenHash,
		&i.Data,
	)
	return i, err
}

const deleteAgentInstance = `-- name: DeleteAgentInstance :exec
DELETE FROM agent_instance WHERE id = $1
`

func (q *Queries) DeleteAgentInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentInstance, id)
	return err
}

const deleteAgentInstanceShare = `-- name: DeleteAgentInstanceShare :execrows
DELETE FROM agent_instance_share s
USING agent_instance i
WHERE s.id = $1
  AND i.id = s.instance_id AND i.user_id = $2
`

type DeleteAgentInstanceShareParams struct {
	ID     uuid.UUID
	UserID string
}

func (q *Queries) DeleteAgentInstanceShare(ctx context.Context, arg DeleteAgentInstanceShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentInstanceShare, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentInstanceByID = `-- name: GetAgentInstanceByID :one
SELECT id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id FROM agent_instance WHERE id = $1
`

func (q *Queries) GetAgentInstanceByID(ctx context.Context, id uuid.UUID) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceByID, id)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const getAgentInstanceByRequest = `-- name: GetAgentInstanceByRequest :one
SELECT id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id FROM agent_instance
WHERE user_id = $1 AND request_id = $2
`

type GetAgentInstanceByRequestParams struct {
	UserID    string
	RequestID string
}

func (q *Queries) GetAgentInstanceByRequest(ctx context.Context, arg GetAgentInstanceByRequestParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceByRequest, arg.UserID, arg.RequestID)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const getAgentInstanceForUpdate = `-- name: GetAgentInstanceForUpdate :one
SELECT id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id FROM agent_instance WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAgentInstanceForUpdate(ctx context.Context, id uuid.UUID) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceForUpdate, id)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const getAgentInstanceForUser = `-- name: GetAgentInstanceForUser :one
SELECT id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id FROM agent_instance WHERE id = $1 AND user_id = $2
`

type GetAgentInstanceForUserParams struct {
	ID     uuid.UUID
	UserID string
}

func (q *Queries) GetAgentInstanceForUser(ctx context.Context, arg GetAgentInstanceForUserParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceForUser, arg.ID, arg.UserID)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const getAgentInstanceShareByTokenHash = `-- name: GetAgentInstanceShareByTokenHash :one
SELECT s.id, s.instance_id, s.permission, s.token_hash, s.data, i.user_id AS owner_user_id
FROM agent_instance_share s
JOIN agent_instance i ON i.id = s.instance_id
WHERE s.token_hash = $1
`

type GetAgentInstanceShareByTokenHashRow struct {
	ID          uuid.UUID
	InstanceID  uuid.UUID
	Permission  string
	TokenHash   []byte
	Data        []byte
	OwnerUserID string
}

// Resolves a share token to the share and the instance's owner.
//
// The owner is joined in because that is what the share grants: the reader is
// authenticated as themselves, and the token widens what that account may read to
// what the *owner* can see. Without the owner's user id the instance lookup would
// run as the visitor and find nothing.
func (q *Queries) GetAgentInstanceShareByTokenHash(ctx context.Context, tokenHash []byte) (GetAgentInstanceShareByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceShareByTokenHash, tokenHash)
	var i GetAgentInstanceShareByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Permission,
		&i.TokenHash,
		&i.Data,
		&i.OwnerUserID,
	)
	return i, err
}

const getLatestRuntimeRevisionForInstance = `-- name: GetLatestRuntimeRevisionForInstance :one
SELECT r.revision, r.namespace, r.agent_template_name, r.agent_template_uid, r.harness_name, r.harness_uid, r.source_snapshot, r.egress_destinations, r.actor_template_atespace, r.actor_template_name, r.actor_template_uid, r.created_at, r.updated_at, r.agent_card, p.agent_template_labels, clock_timestamp()::timestamptz AS db_time
FROM agent_template_harness_pair p
JOIN runtime_revision r ON r.revision = p.latest_successful_revision
WHERE p.namespace = $1
  AND p.namespace = $2
  AND p.agent_template_name = $3
  AND p.harness_name = $4
  AND p.retired_at IS NULL
`

type GetLatestRuntimeRevisionForInstanceParams struct {
	HarnessNamespace       string
	AgentTemplateNamespace string
	AgentTemplateName      string
	HarnessName            string
}

type GetLatestRuntimeRevisionForInstanceRow struct {
	Revision              string
	Namespace             string
	AgentTemplateName     string
	AgentTemplateUid      string
	HarnessName           string
	HarnessUid            string
	SourceSnapshot        []byte
	EgressDestinations    []string
	ActorTemplateAtespace string
	ActorTemplateName     string
	ActorTemplateUid      string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AgentCard             []byte
	AgentTemplateLabels   []byte
	DbTime                time.Time
}

func (q *Queries) GetLatestRuntimeRevisionForInstance(ctx context.Context, arg GetLatestRuntimeRevisionForInstanceParams) (GetLatestRuntimeRevisionForInstanceRow, error) {
	row := q.db.QueryRow(ctx, getLatestRuntimeRevisionForInstance,
		arg.HarnessNamespace,
		arg.AgentTemplateNamespace,
		arg.AgentTemplateName,
		arg.HarnessName,
	)
	var i GetLatestRuntimeRevisionForInstanceRow
	err := row.Scan(
		&i.Revision,
		&i.Namespace,
		&i.AgentTemplateName,
		&i.AgentTemplateUid,
		&i.HarnessName,
		&i.HarnessUid,
		&i.SourceSnapshot,
		&i.EgressDestinations,
		&i.ActorTemplateAtespace,
		&i.ActorTemplateName,
		&i.ActorTemplateUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentCard,
		&i.AgentTemplateLabels,
		&i.DbTime,
	)
	return i, err
}

const insertA2AContext = `-- name: InsertA2AContext :exec
INSERT INTO a2a_context (id, user_id) VALUES ($1, $2)
`

type InsertA2AContextParams struct {
	ID     uuid.UUID
	UserID string
}

func (q *Queries) InsertA2AContext(ctx context.Context, arg InsertA2AContextParams) error {
	_, err := q.db.Exec(ctx, insertA2AContext, arg.ID, arg.UserID)
	return err
}

const insertAgentInstance = `-- name: InsertAgentInstance :one
INSERT INTO agent_instance (id, user_id, request_id, context_id, prepared_revision, source_checkpoint_id, state, operation, labels, data) VALUES ($1, $2, $3, $4, $5, $8::uuid, 'CREATING', 'CREATE', $6, $7)
ON CONFLICT (user_id, request_id) DO NOTHING
RETURNING id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id
`

type InsertAgentInstanceParams struct {
	ID                 uuid.UUID
	UserID             string
	RequestID          string
	ContextID          uuid.UUID
	PreparedRevision   *string
	Labels             []byte
	Data               []byte
	SourceCheckpointID *uuid.UUID
}

func (q *Queries) InsertAgentInstance(ctx context.Context, arg InsertAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, insertAgentInstance,
		arg.ID,
		arg.UserID,
		arg.RequestID,
		arg.ContextID,
		arg.PreparedRevision,
		arg.Labels,
		arg.Data,
		arg.SourceCheckpointID,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const listAgentInstanceShares = `-- name: ListAgentInstanceShares :many
SELECT s.id, s.instance_id, s.permission, s.token_hash, s.data FROM agent_instance_share s
JOIN agent_instance i ON i.id = s.instance_id
WHERE s.instance_id = $1 AND i.user_id = $2
  AND (NULLIF($3::text, '') IS NULL OR s.id > NULLIF($3::text, '')::uuid)
ORDER BY s.id
LIMIT $4
`

type ListAgentInstanceSharesParams struct {
	InstanceID uuid.UUID
	UserID     string
	AfterID    string
	PageSize   int32
}

func (q *Queries) ListAgentInstanceShares(ctx context.Context, arg ListAgentInstanceSharesParams) ([]AgentInstanceShare, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceShares,
		arg.InstanceID,
		arg.UserID,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceShare
	for rows.Next() {
		var i AgentInstanceShare
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Permission,
			&i.TokenHash,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInstances = `-- name: ListAgentInstances :many
SELECT i.id, i.user_id, i.request_id, i.prepared_revision, i.state, i.labels, i.data, i.operation, i.context_id, i.source_checkpoint_id FROM agent_instance i
LEFT JOIN runtime_revision r ON r.revision = i.prepared_revision
WHERE ($1::boolean OR i.user_id = $2)
  AND (NULLIF($3::text, '') IS NULL OR i.id > NULLIF($3::text, '')::uuid)
  AND i.labels @> $4::jsonb
  AND ($5::text = '' OR (r.agent_template_name = $5 AND r.namespace = $6))
  AND ($7::text = '' OR (r.harness_name = $7 AND r.namespace = $8))
ORDER BY i.id
LIMIT $9
`

type ListAgentInstancesParams struct {
	AllUsers               bool
	UserID                 string
	AfterID                string
	MatchLabels            []byte
	AgentTemplate          string
	AgentTemplateNamespace string
	Harness                string
	HarnessNamespace       string
	PageSize               int32
}

// Lists the conversations an instance is, optionally narrowed to one agent.
//
// An agent is an (AgentTemplate, Harness) pair, and the instance row carries
// neither name as a column -- both live inside `data`. They are resolved through
// `prepared_revision`, which is a foreign key to `runtime_revision` and does
// carry them, so the filter needs no new column and matches rows written before
// it existed. An instance with no prepared revision belongs to no pair and
// therefore matches no template or harness filter.
func (q *Queries) ListAgentInstances(ctx context.Context, arg ListAgentInstancesParams) ([]AgentInstance, error) {
	rows, err := q.db.Query(ctx, listAgentInstances,
		arg.AllUsers,
		arg.UserID,
		arg.AfterID,
		arg.MatchLabels,
		arg.AgentTemplate,
		arg.AgentTemplateNamespace,
		arg.Harness,
		arg.HarnessNamespace,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstance
	for rows.Next() {
		var i AgentInstance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.PreparedRevision,
			&i.State,
			&i.Labels,
			&i.Data,
			&i.Operation,
			&i.ContextID,
			&i.SourceCheckpointID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentInstanceReady = `-- name: MarkAgentInstanceReady :one
UPDATE agent_instance
SET state = 'READY', operation = 'NONE', data = $2
WHERE id = $1 AND state = 'CREATING' AND operation = 'CREATE'
RETURNING id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id
`

type MarkAgentInstanceReadyParams struct {
	ID   uuid.UUID
	Data []byte
}

func (q *Queries) MarkAgentInstanceReady(ctx context.Context, arg MarkAgentInstanceReadyParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, markAgentInstanceReady, arg.ID, arg.Data)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const transitionAgentInstance = `-- name: TransitionAgentInstance :one
UPDATE agent_instance
SET state = $1, operation = $2, data = $3
WHERE agent_instance.id = $4
  AND agent_instance.state = $5
  AND agent_instance.operation = $6
  AND (
    $6::text <> 'NONE'
    OR NOT EXISTS (
      SELECT 1 FROM agent_instance_checkpoint c
      WHERE c.source_instance_id = agent_instance.id AND c.state = 'CREATING'
    )
  )
RETURNING id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id
`

type TransitionAgentInstanceParams struct {
	NextState         string
	NextOperation     string
	Data              []byte
	ID                uuid.UUID
	ExpectedState     string
	ExpectedOperation string
}

func (q *Queries) TransitionAgentInstance(ctx context.Context, arg TransitionAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, transitionAgentInstance,
		arg.NextState,
		arg.NextOperation,
		arg.Data,
		arg.ID,
		arg.ExpectedState,
		arg.ExpectedOperation,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}

const updateAgentInstanceName = `-- name: UpdateAgentInstanceName :one
UPDATE agent_instance
SET data = $1
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, request_id, prepared_revision, state, labels, data, operation, context_id, source_checkpoint_id
`

type UpdateAgentInstanceNameParams struct {
	Data   []byte
	ID     uuid.UUID
	UserID string
}

// The store locks the row and changes only the display name in the payload.
func (q *Queries) UpdateAgentInstanceName(ctx context.Context, arg UpdateAgentInstanceNameParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, updateAgentInstanceName, arg.Data, arg.ID, arg.UserID)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.PreparedRevision,
		&i.State,
		&i.Labels,
		&i.Data,
		&i.Operation,
		&i.ContextID,
		&i.SourceCheckpointID,
	)
	return i, err
}
