// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_instance_checkpoints.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const beginDeleteAgentInstanceCheckpoint = `-- name: BeginDeleteAgentInstanceCheckpoint :one
UPDATE agent_instance_checkpoint
SET state = 'DELETING', data = $3
WHERE agent_instance_checkpoint.id = $1 AND agent_instance_checkpoint.user_id = $2
  AND agent_instance_checkpoint.state IN ('READY', 'DELETING')
  AND NOT EXISTS (
      SELECT 1 FROM agent_instance i WHERE i.source_checkpoint_id = agent_instance_checkpoint.id
  )
RETURNING id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels
`

type BeginDeleteAgentInstanceCheckpointParams struct {
	ID     uuid.UUID
	UserID string
	Data   []byte
}

func (q *Queries) BeginDeleteAgentInstanceCheckpoint(ctx context.Context, arg BeginDeleteAgentInstanceCheckpointParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, beginDeleteAgentInstanceCheckpoint, arg.ID, arg.UserID, arg.Data)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const deleteAgentInstanceCheckpoint = `-- name: DeleteAgentInstanceCheckpoint :execrows
DELETE FROM agent_instance_checkpoint
WHERE id = $1 AND user_id = $2 AND state = 'DELETING'
`

type DeleteAgentInstanceCheckpointParams struct {
	ID     uuid.UUID
	UserID string
}

func (q *Queries) DeleteAgentInstanceCheckpoint(ctx context.Context, arg DeleteAgentInstanceCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentInstanceCheckpoint, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeAgentInstanceCheckpoint = `-- name: FinalizeAgentInstanceCheckpoint :one
UPDATE agent_instance_checkpoint
SET state = CASE WHEN $2::text <> '' THEN 'READY' ELSE 'FAILED' END,
    tag_uid = $2,
    snapshot_uri = CASE WHEN $2::text <> '' THEN $3::text ELSE snapshot_uri END,
    data = $4
WHERE id = $1
  AND state = 'CREATING'
RETURNING id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels
`

type FinalizeAgentInstanceCheckpointParams struct {
	ID          uuid.UUID
	TagUid      string
	SnapshotUri string
	Data        []byte
}

func (q *Queries) FinalizeAgentInstanceCheckpoint(ctx context.Context, arg FinalizeAgentInstanceCheckpointParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, finalizeAgentInstanceCheckpoint,
		arg.ID,
		arg.TagUid,
		arg.SnapshotUri,
		arg.Data,
	)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const getAgentInstanceCheckpoint = `-- name: GetAgentInstanceCheckpoint :one
SELECT id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels FROM agent_instance_checkpoint
WHERE id = $1 AND user_id = $2
  -- Lifecycle work also reads creating and deleting checkpoints.
  AND ($3::text IS NULL OR state = $3)
`

type GetAgentInstanceCheckpointParams struct {
	ID     uuid.UUID
	UserID string
	State  *string
}

func (q *Queries) GetAgentInstanceCheckpoint(ctx context.Context, arg GetAgentInstanceCheckpointParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceCheckpoint, arg.ID, arg.UserID, arg.State)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const getAgentInstanceCheckpointByRequest = `-- name: GetAgentInstanceCheckpointByRequest :one
SELECT id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels FROM agent_instance_checkpoint
WHERE user_id = $1 AND request_id = $2
`

type GetAgentInstanceCheckpointByRequestParams struct {
	UserID    string
	RequestID string
}

func (q *Queries) GetAgentInstanceCheckpointByRequest(ctx context.Context, arg GetAgentInstanceCheckpointByRequestParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceCheckpointByRequest, arg.UserID, arg.RequestID)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const getAgentInstanceCheckpointForUpdate = `-- name: GetAgentInstanceCheckpointForUpdate :one
SELECT id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels FROM agent_instance_checkpoint
WHERE id = $1
  -- Only internal finalization explicitly opts out of owner filtering.
  AND ($2::boolean OR user_id = $3)
  AND ($4::text IS NULL OR state = $4)
FOR UPDATE
`

type GetAgentInstanceCheckpointForUpdateParams struct {
	ID       uuid.UUID
	AllUsers bool
	UserID   string
	State    *string
}

func (q *Queries) GetAgentInstanceCheckpointForUpdate(ctx context.Context, arg GetAgentInstanceCheckpointForUpdateParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceCheckpointForUpdate,
		arg.ID,
		arg.AllUsers,
		arg.UserID,
		arg.State,
	)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const getLatestQuiescentAgentInstanceTask = `-- name: GetLatestQuiescentAgentInstanceTask :one
SELECT latest.context_id, latest.id, latest.state, latest.status_timestamp, latest.data, latest.created_at, latest.updated_at, latest.initial_message_id, latest.request_hash, latest.snapshot_atespace, latest.snapshot_uri, latest.snapshot_content_scope, latest.history_sequence
FROM (
    SELECT context_id, id, state, status_timestamp, data, created_at, updated_at, initial_message_id, request_hash, snapshot_atespace, snapshot_uri, snapshot_content_scope, history_sequence FROM agent_instance_task
    WHERE agent_instance_task.context_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT 1
) latest
WHERE NOT EXISTS (
    SELECT 1 FROM agent_instance_task active
    WHERE active.context_id = $1
      AND active.state NOT IN (
          'TASK_STATE_COMPLETED',
          'TASK_STATE_CANCELED',
          'TASK_STATE_FAILED',
          'TASK_STATE_REJECTED',
          'TASK_STATE_INPUT_REQUIRED',
          'TASK_STATE_AUTH_REQUIRED'
      )
)
`

func (q *Queries) GetLatestQuiescentAgentInstanceTask(ctx context.Context, contextID uuid.UUID) (AgentInstanceTask, error) {
	row := q.db.QueryRow(ctx, getLatestQuiescentAgentInstanceTask, contextID)
	var i AgentInstanceTask
	err := row.Scan(
		&i.ContextID,
		&i.ID,
		&i.State,
		&i.StatusTimestamp,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialMessageID,
		&i.RequestHash,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.HistorySequence,
	)
	return i, err
}

const insertAgentInstanceCheckpoint = `-- name: InsertAgentInstanceCheckpoint :one
INSERT INTO agent_instance_checkpoint (id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, source_context_id, prepared_revision, source_labels, data, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'CREATING')
ON CONFLICT DO NOTHING
RETURNING id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels
`

type InsertAgentInstanceCheckpointParams struct {
	ID                   uuid.UUID
	SourceInstanceID     uuid.UUID
	UserID               string
	RequestID            string
	HeadTaskID           string
	HistorySequence      int64
	SnapshotAtespace     string
	SnapshotUri          string
	SnapshotContentScope string
	SourceContextID      uuid.UUID
	PreparedRevision     *string
	SourceLabels         []byte
	Data                 []byte
}

func (q *Queries) InsertAgentInstanceCheckpoint(ctx context.Context, arg InsertAgentInstanceCheckpointParams) (AgentInstanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertAgentInstanceCheckpoint,
		arg.ID,
		arg.SourceInstanceID,
		arg.UserID,
		arg.RequestID,
		arg.HeadTaskID,
		arg.HistorySequence,
		arg.SnapshotAtespace,
		arg.SnapshotUri,
		arg.SnapshotContentScope,
		arg.SourceContextID,
		arg.PreparedRevision,
		arg.SourceLabels,
		arg.Data,
	)
	var i AgentInstanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.SourceInstanceID,
		&i.UserID,
		&i.RequestID,
		&i.HeadTaskID,
		&i.HistorySequence,
		&i.SnapshotAtespace,
		&i.SnapshotUri,
		&i.SnapshotContentScope,
		&i.TagUid,
		&i.State,
		&i.Data,
		&i.SourceContextID,
		&i.PreparedRevision,
		&i.SourceLabels,
	)
	return i, err
}

const listAgentInstanceCheckpointEvents = `-- name: ListAgentInstanceCheckpointEvents :many
SELECT e.sequence, e.context_id, e.task_id, e.data, e.created_at, e.message_id
FROM agent_instance_checkpoint c
JOIN agent_instance_task_event e
  ON e.context_id = c.source_context_id
 AND e.sequence <= c.history_sequence
WHERE c.id = $1
ORDER BY e.sequence
`

func (q *Queries) ListAgentInstanceCheckpointEvents(ctx context.Context, checkpointID uuid.UUID) ([]AgentInstanceTaskEvent, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceCheckpointEvents, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceTaskEvent
	for rows.Next() {
		var i AgentInstanceTaskEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.ContextID,
			&i.TaskID,
			&i.Data,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInstanceCheckpointTasks = `-- name: ListAgentInstanceCheckpointTasks :many
SELECT t.context_id, t.id, t.state, t.status_timestamp, t.data, t.created_at, t.updated_at, t.initial_message_id, t.request_hash, t.snapshot_atespace, t.snapshot_uri, t.snapshot_content_scope, t.history_sequence
FROM agent_instance_checkpoint c
JOIN agent_instance_task head
  ON head.context_id = c.source_context_id AND head.id = c.head_task_id
JOIN agent_instance_task t
  ON t.context_id = c.source_context_id
 AND (t.created_at, t.id) <= (head.created_at, head.id)
WHERE c.id = $1
ORDER BY t.created_at, t.id
`

func (q *Queries) ListAgentInstanceCheckpointTasks(ctx context.Context, checkpointID uuid.UUID) ([]AgentInstanceTask, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceCheckpointTasks, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceTask
	for rows.Next() {
		var i AgentInstanceTask
		if err := rows.Scan(
			&i.ContextID,
			&i.ID,
			&i.State,
			&i.StatusTimestamp,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialMessageID,
			&i.RequestHash,
			&i.SnapshotAtespace,
			&i.SnapshotUri,
			&i.SnapshotContentScope,
			&i.HistorySequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInstanceCheckpoints = `-- name: ListAgentInstanceCheckpoints :many
SELECT id, source_instance_id, user_id, request_id, head_task_id, history_sequence, snapshot_atespace, snapshot_uri, snapshot_content_scope, tag_uid, state, data, source_context_id, prepared_revision, source_labels FROM agent_instance_checkpoint
WHERE source_instance_id = $1
  AND user_id = $2
  AND state = 'READY'
  AND (NULLIF($3::text, '') IS NULL OR id > NULLIF($3::text, '')::uuid)
ORDER BY id
LIMIT $4
`

type ListAgentInstanceCheckpointsParams struct {
	SourceInstanceID uuid.UUID
	UserID           string
	AfterID          string
	PageSize         int32
}

func (q *Queries) ListAgentInstanceCheckpoints(ctx context.Context, arg ListAgentInstanceCheckpointsParams) ([]AgentInstanceCheckpoint, error) {
	rows, err := q.db.Query(ctx, listAgentInstanceCheckpoints,
		arg.SourceInstanceID,
		arg.UserID,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstanceCheckpoint
	for rows.Next() {
		var i AgentInstanceCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.SourceInstanceID,
			&i.UserID,
			&i.RequestID,
			&i.HeadTaskID,
			&i.HistorySequence,
			&i.SnapshotAtespace,
			&i.SnapshotUri,
			&i.SnapshotContentScope,
			&i.TagUid,
			&i.State,
			&i.Data,
			&i.SourceContextID,
			&i.PreparedRevision,
			&i.SourceLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
