// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AgentInstance struct {
	ID                 uuid.UUID
	UserID             string
	RequestID          string
	PreparedRevision   *string
	State              string
	Labels             []byte
	Data               []byte
	Operation          string
	ContextID          uuid.UUID
	SourceCheckpointID *uuid.UUID
}

type AgentInstanceCheckpoint struct {
	ID                   uuid.UUID
	SourceInstanceID     uuid.UUID
	UserID               string
	RequestID            string
	HeadTaskID           string
	HistorySequence      int64
	SnapshotAtespace     string
	SnapshotUri          string
	SnapshotContentScope string
	TagUid               string
	State                string
	Data                 []byte
	SourceContextID      uuid.UUID
	PreparedRevision     *string
	SourceLabels         []byte
}

type AgentInstanceShare struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Permission string
	TokenHash  []byte
	Data       []byte
}

type AgentInstanceTask struct {
	ContextID            uuid.UUID
	ID                   string
	State                string
	StatusTimestamp      *time.Time
	Data                 []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	InitialMessageID     *string
	RequestHash          []byte
	SnapshotAtespace     *string
	SnapshotUri          *string
	SnapshotContentScope *string
	HistorySequence      *int64
}

type AgentInstanceTaskEvent struct {
	Sequence  int64
	ContextID uuid.UUID
	TaskID    *string
	Data      []byte
	CreatedAt time.Time
	MessageID *string
}

type Memory struct {
	ID          string
	AgentName   *string
	UserID      *string
	Content     *string
	Embedding   pgvector_go.Vector
	Metadata    *string
	CreatedAt   *time.Time
	ExpiresAt   *time.Time
	AccessCount *int64
}

type RuntimeRevision struct {
	Revision              string
	Namespace             string
	AgentTemplateName     string
	AgentTemplateUid      string
	HarnessName           string
	HarnessUid            string
	SourceSnapshot        []byte
	EgressDestinations    []string
	ActorTemplateAtespace string
	ActorTemplateName     string
	ActorTemplateUid      string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AgentCard             []byte
	DeletionStartedAt     *time.Time
}

type Tool struct {
	ID          string
	ServerName  string
	GroupKind   string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	DeletedAt   *time.Time
	Description *string
}

type Toolserver struct {
	Name          string
	GroupKind     string
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
	Description   *string
	LastConnected *time.Time
}
