// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_revisions.sql

package dbgen

import (
	"context"
)

const claimRuntimeRevisionDeletion = `-- name: ClaimRuntimeRevisionDeletion :execrows
UPDATE runtime_revision
SET deletion_started_at = COALESCE(deletion_started_at, NOW())
WHERE runtime_revision.revision = $1
  AND runtime_revision.revision IN (SELECT revision FROM unreferenced_runtime_revision)
`

func (q *Queries) ClaimRuntimeRevisionDeletion(ctx context.Context, revision string) (int64, error) {
	result, err := q.db.Exec(ctx, claimRuntimeRevisionDeletion, revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnreferencedRuntimeRevision = `-- name: DeleteUnreferencedRuntimeRevision :exec
DELETE FROM runtime_revision r
WHERE r.revision = $1
  AND r.deletion_started_at IS NOT NULL
`

func (q *Queries) DeleteUnreferencedRuntimeRevision(ctx context.Context, revision string) error {
	_, err := q.db.Exec(ctx, deleteUnreferencedRuntimeRevision, revision)
	return err
}

const getRuntimeRevision = `-- name: GetRuntimeRevision :one
SELECT revision, namespace, agent_template_name, agent_template_uid, harness_name, harness_uid, source_snapshot, egress_destinations, actor_template_atespace, actor_template_name, actor_template_uid, created_at, updated_at, agent_card, deletion_started_at FROM runtime_revision WHERE revision = $1
`

func (q *Queries) GetRuntimeRevision(ctx context.Context, revision string) (RuntimeRevision, error) {
	row := q.db.QueryRow(ctx, getRuntimeRevision, revision)
	var i RuntimeRevision
	err := row.Scan(
		&i.Revision,
		&i.Namespace,
		&i.AgentTemplateName,
		&i.AgentTemplateUid,
		&i.HarnessName,
		&i.HarnessUid,
		&i.SourceSnapshot,
		&i.EgressDestinations,
		&i.ActorTemplateAtespace,
		&i.ActorTemplateName,
		&i.ActorTemplateUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentCard,
		&i.DeletionStartedAt,
	)
	return i, err
}

const listActorTemplateHarnesses = `-- name: ListActorTemplateHarnesses :many
SELECT actor_template_atespace, actor_template_name, actor_template_uid, harness_name
FROM runtime_revision
`

type ListActorTemplateHarnessesRow struct {
	ActorTemplateAtespace string
	ActorTemplateName     string
	ActorTemplateUid      string
	HarnessName           string
}

func (q *Queries) ListActorTemplateHarnesses(ctx context.Context) ([]ListActorTemplateHarnessesRow, error) {
	rows, err := q.db.Query(ctx, listActorTemplateHarnesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActorTemplateHarnessesRow
	for rows.Next() {
		var i ListActorTemplateHarnessesRow
		if err := rows.Scan(
			&i.ActorTemplateAtespace,
			&i.ActorTemplateName,
			&i.ActorTemplateUid,
			&i.HarnessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedRuntimeRevisions = `-- name: ListUnreferencedRuntimeRevisions :many
SELECT revision, namespace, agent_template_name, agent_template_uid, harness_name, harness_uid, source_snapshot, egress_destinations, actor_template_atespace, actor_template_name, actor_template_uid, created_at, updated_at, agent_card, deletion_started_at FROM runtime_revision r
WHERE r.revision IN (SELECT revision FROM unreferenced_runtime_revision)
`

func (q *Queries) ListUnreferencedRuntimeRevisions(ctx context.Context) ([]RuntimeRevision, error) {
	rows, err := q.db.Query(ctx, listUnreferencedRuntimeRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeRevision
	for rows.Next() {
		var i RuntimeRevision
		if err := rows.Scan(
			&i.Revision,
			&i.Namespace,
			&i.AgentTemplateName,
			&i.AgentTemplateUid,
			&i.HarnessName,
			&i.HarnessUid,
			&i.SourceSnapshot,
			&i.EgressDestinations,
			&i.ActorTemplateAtespace,
			&i.ActorTemplateName,
			&i.ActorTemplateUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentCard,
			&i.DeletionStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuntimeRevision = `-- name: LockRuntimeRevision :one
SELECT revision, namespace, agent_template_name, agent_template_uid, harness_name, harness_uid, source_snapshot, egress_destinations, actor_template_atespace, actor_template_name, actor_template_uid, created_at, updated_at, agent_card, deletion_started_at FROM runtime_revision WHERE revision = $1 FOR UPDATE
`

// The store locks first, then checks eligibility in a separate statement so
// references committed while waiting for the lock are visible to the claim.
func (q *Queries) LockRuntimeRevision(ctx context.Context, revision string) (RuntimeRevision, error) {
	row := q.db.QueryRow(ctx, lockRuntimeRevision, revision)
	var i RuntimeRevision
	err := row.Scan(
		&i.Revision,
		&i.Namespace,
		&i.AgentTemplateName,
		&i.AgentTemplateUid,
		&i.HarnessName,
		&i.HarnessUid,
		&i.SourceSnapshot,
		&i.EgressDestinations,
		&i.ActorTemplateAtespace,
		&i.ActorTemplateName,
		&i.ActorTemplateUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentCard,
		&i.DeletionStartedAt,
	)
	return i, err
}

const markRuntimeRevisionSuccessful = `-- name: MarkRuntimeRevisionSuccessful :exec
UPDATE agent_template_harness_pair
SET latest_successful_revision = $1, updated_at = NOW()
WHERE namespace = $2
  AND agent_template_uid = $3
  AND harness_uid = $4
  AND desired_revision = $1
  AND retired_at IS NULL
`

type MarkRuntimeRevisionSuccessfulParams struct {
	Revision         *string
	Namespace        string
	AgentTemplateUid string
	HarnessUid       string
}

func (q *Queries) MarkRuntimeRevisionSuccessful(ctx context.Context, arg MarkRuntimeRevisionSuccessfulParams) error {
	_, err := q.db.Exec(ctx, markRuntimeRevisionSuccessful,
		arg.Revision,
		arg.Namespace,
		arg.AgentTemplateUid,
		arg.HarnessUid,
	)
	return err
}

const releaseRetiredRuntimeRevisionReferences = `-- name: ReleaseRetiredRuntimeRevisionReferences :exec
UPDATE agent_template_harness_pair
SET latest_successful_revision = NULL, updated_at = NOW()
WHERE retired_at IS NOT NULL AND latest_successful_revision = $1
`

// Retired pairs no longer retain runtime inputs. Release their historical
// success pointers in the same transaction as deletion, preserving RESTRICT
// protection for active pairs, instances, and checkpoints.
func (q *Queries) ReleaseRetiredRuntimeRevisionReferences(ctx context.Context, latestSuccessfulRevision *string) error {
	_, err := q.db.Exec(ctx, releaseRetiredRuntimeRevisionReferences, latestSuccessfulRevision)
	return err
}

const retireAgentTemplateHarnessPair = `-- name: RetireAgentTemplateHarnessPair :exec
UPDATE agent_template_harness_pair
SET retired_at = COALESCE(retired_at, NOW()), updated_at = NOW()
WHERE namespace = $1 AND agent_template_name = $2 AND harness_name = $3
`

type RetireAgentTemplateHarnessPairParams struct {
	Namespace         string
	AgentTemplateName string
	HarnessName       string
}

func (q *Queries) RetireAgentTemplateHarnessPair(ctx context.Context, arg RetireAgentTemplateHarnessPairParams) error {
	_, err := q.db.Exec(ctx, retireAgentTemplateHarnessPair, arg.Namespace, arg.AgentTemplateName, arg.HarnessName)
	return err
}

const retireAgentTemplateHarnessPairs = `-- name: RetireAgentTemplateHarnessPairs :exec
UPDATE agent_template_harness_pair
SET retired_at = COALESCE(retired_at, NOW()), updated_at = NOW()
WHERE namespace = $1 AND agent_template_name = $2
`

type RetireAgentTemplateHarnessPairsParams struct {
	Namespace         string
	AgentTemplateName string
}

func (q *Queries) RetireAgentTemplateHarnessPairs(ctx context.Context, arg RetireAgentTemplateHarnessPairsParams) error {
	_, err := q.db.Exec(ctx, retireAgentTemplateHarnessPairs, arg.Namespace, arg.AgentTemplateName)
	return err
}

const retireOtherAgentTemplateHarnessPairs = `-- name: RetireOtherAgentTemplateHarnessPairs :exec
UPDATE agent_template_harness_pair
SET retired_at = COALESCE(retired_at, NOW()), updated_at = NOW()
WHERE namespace = $1
  AND agent_template_uid = $2
  AND NOT (harness_name = ANY($3::text[]))
`

type RetireOtherAgentTemplateHarnessPairsParams struct {
	Namespace        string
	AgentTemplateUid string
	HarnessNames     []string
}

func (q *Queries) RetireOtherAgentTemplateHarnessPairs(ctx context.Context, arg RetireOtherAgentTemplateHarnessPairsParams) error {
	_, err := q.db.Exec(ctx, retireOtherAgentTemplateHarnessPairs, arg.Namespace, arg.AgentTemplateUid, arg.HarnessNames)
	return err
}

const retireReplacedAgentTemplateHarnessPairs = `-- name: RetireReplacedAgentTemplateHarnessPairs :exec
UPDATE agent_template_harness_pair
SET retired_at = NOW(), updated_at = NOW()
WHERE namespace = $1 AND agent_template_name = $2 AND harness_name = $3
  AND retired_at IS NULL
  AND (agent_template_uid, harness_uid) IS DISTINCT FROM ($4::text, $5::text)
`

type RetireReplacedAgentTemplateHarnessPairsParams struct {
	Namespace         string
	AgentTemplateName string
	HarnessName       string
	AgentTemplateUid  string
	HarnessUid        string
}

func (q *Queries) RetireReplacedAgentTemplateHarnessPairs(ctx context.Context, arg RetireReplacedAgentTemplateHarnessPairsParams) error {
	_, err := q.db.Exec(ctx, retireReplacedAgentTemplateHarnessPairs,
		arg.Namespace,
		arg.AgentTemplateName,
		arg.HarnessName,
		arg.AgentTemplateUid,
		arg.HarnessUid,
	)
	return err
}

const upsertAgentTemplateHarnessPair = `-- name: UpsertAgentTemplateHarnessPair :exec
INSERT INTO agent_template_harness_pair (
    namespace, agent_template_name, agent_template_uid,
    harness_name, harness_uid, desired_revision, agent_template_labels, retired_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NULL)
ON CONFLICT (namespace, agent_template_uid, harness_uid) DO UPDATE SET
    agent_template_name = EXCLUDED.agent_template_name,
    harness_name = EXCLUDED.harness_name,
    desired_revision = EXCLUDED.desired_revision,
    agent_template_labels = EXCLUDED.agent_template_labels,
    retired_at = NULL,
    updated_at = NOW()
`

type UpsertAgentTemplateHarnessPairParams struct {
	Namespace           string
	AgentTemplateName   string
	AgentTemplateUid    string
	HarnessName         string
	HarnessUid          string
	DesiredRevision     string
	AgentTemplateLabels []byte
}

func (q *Queries) UpsertAgentTemplateHarnessPair(ctx context.Context, arg UpsertAgentTemplateHarnessPairParams) error {
	_, err := q.db.Exec(ctx, upsertAgentTemplateHarnessPair,
		arg.Namespace,
		arg.AgentTemplateName,
		arg.AgentTemplateUid,
		arg.HarnessName,
		arg.HarnessUid,
		arg.DesiredRevision,
		arg.AgentTemplateLabels,
	)
	return err
}

const upsertRuntimeRevision = `-- name: UpsertRuntimeRevision :execrows
INSERT INTO runtime_revision (
    revision, namespace, agent_template_name, agent_template_uid,
    harness_name, harness_uid, source_snapshot, agent_card, egress_destinations,
    actor_template_atespace, actor_template_name, actor_template_uid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12
)
ON CONFLICT (revision) DO UPDATE SET
    actor_template_uid = EXCLUDED.actor_template_uid,
    updated_at = NOW()
WHERE runtime_revision.deletion_started_at IS NULL
`

type UpsertRuntimeRevisionParams struct {
	Revision              string
	Namespace             string
	AgentTemplateName     string
	AgentTemplateUid      string
	HarnessName           string
	HarnessUid            string
	SourceSnapshot        []byte
	AgentCard             []byte
	EgressDestinations    []string
	ActorTemplateAtespace string
	ActorTemplateName     string
	ActorTemplateUid      string
}

// The revision digest pins the card. Reconciliation only refreshes runtime identity.
func (q *Queries) UpsertRuntimeRevision(ctx context.Context, arg UpsertRuntimeRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRuntimeRevision,
		arg.Revision,
		arg.Namespace,
		arg.AgentTemplateName,
		arg.AgentTemplateUid,
		arg.HarnessName,
		arg.HarnessUid,
		arg.SourceSnapshot,
		arg.AgentCard,
		arg.EgressDestinations,
		arg.ActorTemplateAtespace,
		arg.ActorTemplateName,
		arg.ActorTemplateUid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
